import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions/v1';
import { HttpsError, CallableContext } from 'firebase-functions/v1/https';

admin.initializeApp();

const db: admin.firestore.Firestore = admin.firestore();
const auth: admin.auth.Auth = admin.auth();

type Role = 'parent' | 'teacher' | 'admin';
type UserStatus = 'pending_approval' | 'active' | 'rejected';

interface InviteCode {
    role: 'teacher' | 'admin';
    isActive: boolean;
    expiresAt?: string;
    maxUses: number;
    consumedCount: number;
    createdBy: string;
    createdAt: string;
}

const ROLE_REQUIREMENTS: Record<Role, { needsInvite: boolean }> = {
    parent: { needsInvite: false },
    teacher: { needsInvite: true },
    admin: { needsInvite: true },
};

/** Gatekeeper for privileged (one-click) actions. Rejects unauthenticated,
 * non-admin, or non-active callers regardless of what data they pass. */
function requireAdmin(context: CallableContext): void {
    const claims = context.auth?.token;
    if (!claims || claims.role !== 'admin' || claims.status !== 'active') {
        throw new HttpsError('permission-denied', 'Admin privileges required.');
    }
}

/** Issue (or clear) role + status custom claims. Custom claims ride the Auth
 * token, so every app request — including client-side runtime guards and
 * Firestore security rules reading request.auth.token — is enforced
 * server-side at the token level, not just in-app. */
async function setUserClaims(uid: string, role: Role, status: UserStatus): Promise<void> {
    const claims: Record<string, string> = { role, status };
    await auth.setCustomUserClaims(uid, claims);
}

/**
 * Completes registration for a self-registered user.
 *
 * - parents: no invite needed; active immediately (their data is scoped to
 *   their own child(ren), enforced by rules + queries).
 * - teachers/admins: must supply a valid, unexpired, unconsumed invite code
 *   generated by an admin. Claims stay `pending_approval` until an admin
 *   approves via `adminApprove`.
 */
export const finalizeRegistration = functions.https.onCall(async (data, context) => {
    const uid = data?.uid as string | undefined;
    const role = data?.role as Role | undefined;
    const inviteCode = (data?.inviteCode as string | undefined)?.trim() || undefined;

    if (!uid || !role || !(role in ROLE_REQUIREMENTS)) {
        throw new HttpsError('invalid-argument', 'uid and a valid role are required.');
    }

    // Only allow finalizing your OWN account from the client.
    if (!context.auth || context.auth.uid !== uid) {
        throw new HttpsError('permission-denied', 'You can only finalize your own registration.');
    }

    const userRef = db.collection('users').doc(uid);

    if (ROLE_REQUIREMENTS[role].needsInvite) {
        if (!inviteCode) {
            throw new HttpsError('invalid-argument', 'An invite code is required for this role.');
        }

        const inviteRef = db.collection('inviteCodes').doc(inviteCode);
        const inviteSnap = await inviteRef.get();
        if (!inviteSnap.exists) {
            throw new HttpsError('not-found', 'Invalid invite code.');
        }

        const invite = inviteSnap.data() as InviteCode;
        if (!invite.isActive) {
            throw new HttpsError('failed-precondition', 'This invite code is no longer active.');
        }
        if (invite.role !== role) {
            throw new HttpsError('invalid-argument', `This invite code is for ${invite.role} accounts only.`);
        }
        if (invite.expiresAt && new Date(invite.expiresAt) < new Date()) {
            throw new HttpsError('failed-precondition', 'This invite code has expired.');
        }
        if (invite.consumedCount >= invite.maxUses) {
            throw new HttpsError('resource-exhausted', 'This invite code has reached its usage limit.');
        }

        await inviteRef.update({
            consumedCount: admin.firestore.FieldValue.increment(1),
        });

        // Staff accounts require admin approval before use.
        await setUserClaims(uid, role, 'pending_approval');
        await userRef.update({
            role,
            status: 'pending_approval',
            inviteCode,
            invitedBy: invite.createdBy,
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });

        return { status: 'pending_approval', role };
    }

    // Parents: active immediately.
    await setUserClaims(uid, 'parent', 'active');
    await userRef.update({
        role: 'parent',
        status: 'active',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    return { status: 'active', role: 'parent' };
});

/**
 * Admin-only decision on a pending_approval user. Approving flips the user's
 * custom claims to `active` (unblocking the whole app server-side) and writes
 * a notification so the affected user sees the outcome.
 */
export const adminApprove = functions.https.onCall(async (data, context) => {
    requireAdmin(context);

    const targetUid = data?.targetUid as string | undefined;
    const approve = data?.approve as boolean | undefined;
    const reason = (data?.reason as string | undefined) || '';

    if (!targetUid || typeof approve !== 'boolean') {
        throw new HttpsError('invalid-argument', 'targetUid and a boolean approve are required.');
    }

    const targetUser = await auth.getUser(targetUid);
    const role = (targetUser.customClaims?.role as Role) || 'parent';
    const status: UserStatus = approve ? 'active' : 'rejected';

    await setUserClaims(targetUid, role, status);

    const userRef = db.collection('users').doc(targetUid);
    const userSnap = await userRef.get();
    const schoolId = (userSnap.data()?.schoolId as string) || 'oakridge-academy';

    await userRef.update({
        status,
        ...(reason ? { rejectionReason: reason } : {}),
        reviewedBy: context.auth?.uid ?? null,
        reviewedAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    await db.collection('notifications').add({
        schoolId,
        recipientId: targetUid,
        recipientType: 'teacher',
        type: 'system',
        title: approve ? 'Account Approved' : 'Account Rejected',
        message: approve
            ? 'Your account has been approved. You can now sign in to use the app.'
            : `Your account was not approved${reason ? `: ${reason}` : ''}. Contact your administrator.`,
        data: { decision: status },
        isRead: false,
        priority: 'high',
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    return { status, role };
});

/** Returns the caller's current claims (used to detect pending/rejected state
 * without a reload, e.g. after an admin approves them). */
export const getMyClaims = functions.https.onCall(async (_data, context) => {
    if (!context.auth) {
        throw new HttpsError('unauthenticated', 'You must be signed in.');
    }
    return {
        role: context.auth.token.role || null,
        status: context.auth.token.status || null,
    };
});
