"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.getMyClaims = exports.adminApprove = exports.finalizeRegistration = void 0;
const admin = __importStar(require("firebase-admin"));
const functions = __importStar(require("firebase-functions/v1"));
const https_1 = require("firebase-functions/v1/https");
admin.initializeApp();
const db = admin.firestore();
const auth = admin.auth();
const ROLE_REQUIREMENTS = {
    parent: { needsInvite: false },
    teacher: { needsInvite: true },
    admin: { needsInvite: true },
};
/** Gatekeeper for privileged (one-click) actions. Rejects unauthenticated,
 * non-admin, or non-active callers regardless of what data they pass. */
function requireAdmin(context) {
    const claims = context.auth?.token;
    if (!claims || claims.role !== 'admin' || claims.status !== 'active') {
        throw new https_1.HttpsError('permission-denied', 'Admin privileges required.');
    }
}
/** Issue (or clear) role + status custom claims. Custom claims ride the Auth
 * token, so every app request — including client-side runtime guards and
 * Firestore security rules reading request.auth.token — is enforced
 * server-side at the token level, not just in-app. */
async function setUserClaims(uid, role, status) {
    const claims = { role, status };
    await auth.setCustomUserClaims(uid, claims);
}
/**
 * Completes registration for a self-registered user.
 *
 * - parents: no invite needed; active immediately (their data is scoped to
 *   their own child(ren), enforced by rules + queries).
 * - teachers/admins: must supply a valid, unexpired, unconsumed invite code
 *   generated by an admin. Claims stay `pending_approval` until an admin
 *   approves via `adminApprove`.
 */
exports.finalizeRegistration = functions.https.onCall(async (data, context) => {
    const uid = data?.uid;
    const role = data?.role;
    const inviteCode = data?.inviteCode?.trim() || undefined;
    if (!uid || !role || !(role in ROLE_REQUIREMENTS)) {
        throw new https_1.HttpsError('invalid-argument', 'uid and a valid role are required.');
    }
    // Only allow finalizing your OWN account from the client.
    if (!context.auth || context.auth.uid !== uid) {
        throw new https_1.HttpsError('permission-denied', 'You can only finalize your own registration.');
    }
    const userRef = db.collection('users').doc(uid);
    if (ROLE_REQUIREMENTS[role].needsInvite) {
        if (!inviteCode) {
            throw new https_1.HttpsError('invalid-argument', 'An invite code is required for this role.');
        }
        const inviteRef = db.collection('inviteCodes').doc(inviteCode);
        const inviteSnap = await inviteRef.get();
        if (!inviteSnap.exists) {
            throw new https_1.HttpsError('not-found', 'Invalid invite code.');
        }
        const invite = inviteSnap.data();
        if (!invite.isActive) {
            throw new https_1.HttpsError('failed-precondition', 'This invite code is no longer active.');
        }
        if (invite.role !== role) {
            throw new https_1.HttpsError('invalid-argument', `This invite code is for ${invite.role} accounts only.`);
        }
        if (invite.expiresAt && new Date(invite.expiresAt) < new Date()) {
            throw new https_1.HttpsError('failed-precondition', 'This invite code has expired.');
        }
        if (invite.consumedCount >= invite.maxUses) {
            throw new https_1.HttpsError('resource-exhausted', 'This invite code has reached its usage limit.');
        }
        await inviteRef.update({
            consumedCount: admin.firestore.FieldValue.increment(1),
        });
        // Staff accounts require admin approval before use.
        await setUserClaims(uid, role, 'pending_approval');
        await userRef.update({
            role,
            status: 'pending_approval',
            inviteCode,
            invitedBy: invite.createdBy,
            updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
        return { status: 'pending_approval', role };
    }
    // Parents: active immediately.
    await setUserClaims(uid, 'parent', 'active');
    await userRef.update({
        role: 'parent',
        status: 'active',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    return { status: 'active', role: 'parent' };
});
/**
 * Admin-only decision on a pending_approval user. Approving flips the user's
 * custom claims to `active` (unblocking the whole app server-side) and writes
 * a notification so the affected user sees the outcome.
 */
exports.adminApprove = functions.https.onCall(async (data, context) => {
    requireAdmin(context);
    const targetUid = data?.targetUid;
    const approve = data?.approve;
    const reason = data?.reason || '';
    if (!targetUid || typeof approve !== 'boolean') {
        throw new https_1.HttpsError('invalid-argument', 'targetUid and a boolean approve are required.');
    }
    const targetUser = await auth.getUser(targetUid);
    const role = targetUser.customClaims?.role || 'parent';
    const status = approve ? 'active' : 'rejected';
    await setUserClaims(targetUid, role, status);
    const userRef = db.collection('users').doc(targetUid);
    const userSnap = await userRef.get();
    const schoolId = userSnap.data()?.schoolId || 'oakridge-academy';
    await userRef.update({
        status,
        ...(reason ? { rejectionReason: reason } : {}),
        reviewedBy: context.auth?.uid ?? null,
        reviewedAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    await db.collection('notifications').add({
        schoolId,
        recipientId: targetUid,
        recipientType: 'teacher',
        type: 'system',
        title: approve ? 'Account Approved' : 'Account Rejected',
        message: approve
            ? 'Your account has been approved. You can now sign in to use the app.'
            : `Your account was not approved${reason ? `: ${reason}` : ''}. Contact your administrator.`,
        data: { decision: status },
        isRead: false,
        priority: 'high',
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    return { status, role };
});
/** Returns the caller's current claims (used to detect pending/rejected state
 * without a reload, e.g. after an admin approves them). */
exports.getMyClaims = functions.https.onCall(async (_data, context) => {
    if (!context.auth) {
        throw new https_1.HttpsError('unauthenticated', 'You must be signed in.');
    }
    return {
        role: context.auth.token.role || null,
        status: context.auth.token.status || null,
    };
});
//# sourceMappingURL=index.js.map